language: go

go:
  - "1.11.x"

addons:
  sonarcloud:
    organization: "bazo-blockchain"

script:
  - go test -v ./... -coverprofile=coverage.out -coverpkg=./...
  - go run main.go compile program.lazo
  - go run main.go exec program.bc
  - sonar-scanner

after_success:
  - go build