language: go

go:
  - "1.11.x"

addons:
  sonarcloud:
    organization: "bazo-blockchain"

script:
  - go test -v ./... -coverprofile=coverage.out -coverpkg=./...
  - sonar-scanner

after_success:
  - go build