language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

addons:
  sonarcloud:
    organization: "bazo-blockchain"

script:
  - go test -v ./... -coverprofile=coverage.out -coverpkg=./...
  - go run main.go run program.lazo
  - sonar-scanner

after_success:
  - go build