#!/bin/sh

# Format the staged Go files only
for i in $(git diff --name-only --cached --diff-filter=d | grep ".go"); do
    formattedFile=$(gofmt -l -w -s "$i")
    [[ -z "$formattedFile" ]] || echo "Auto formatted: $formattedFile"
    git add "$i";
done;